apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terraspinrestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraspinrestapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: terraspinrestapp
    spec:
      containers:
        - image: 'docker.io/opsmx11/terraspinrest:5.0'
          imagePullPolicy: Always
          name: terraspinrest
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /home/terraspin/opsmx/app/config/
              readOnly: true
              name: opsmx-terraspin-backend-config
      volumes:
        - secret:
            secretName: terraspinbackendconfig
          name: opsmx-terraspin-backend-config


---
apiVersion: v1
kind: Service
metadata:
  name: terraspinrestappservice
spec:
  ports:
    - name: restappfrontend
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: terraspinrestapp
  type: LoadBalancer

